example/components/CartUI/index.js
example/components/ProductFormUI/index.js
example/views/ProductOptionExample/index.js
src/components/Cart/index.js
src/components/ProductForm/index.js
src/components/ProductIngredient/index.js
src/components/ProductOptionSuboption/index.js
src/contexts/OrderContext/index.js

- Improve ProductIngredient
- Improve ProductOption
- Improve ProductOptionSuboption
- Improve ProductForm

Cart Component

---

cypress/integration/naked/searchOptions.spec.js
example/App.js
example/components/MomentOptionUI/index.js
example/components/SearchOptionsUI/index.js
example/views/Home/index.js
example/views/SearchOptionsExample/index.js
src/components/MomentOption/index.js
src/components/SearchOptions/index.js
src/contexts/OrderContext/index.js

Search options

---

example/components/BaseComponentUI/index.js
example/views/BaseComponentExample/index.js
src/components/BaseComponent/index.js

<h1>Description</h1>
<p>Base components are added for the functional, example and UI component, with the goal of making development much faster ⚡ </p>

Base component

---

cypress/integration/naked/paymentOptionCash.spec.js
cypress/integration/naked/paymentOptionStripeDirect.spec.js
example/App.js
example/components/PaymentOptionCashUI/index.js
example/components/PaymentOptionPaypalUI/index.js
example/components/PaymentOptionStripeDirectUI/index.js
example/components/PaymentOptionStripeRedirectUI/index.js
example/components/PaymentOptionStripeUI/index.js
example/components/StripeElementsFormUI/CardFormUI/index.js
example/components/StripeElementsFormUI/CardFormUI/style.css
example/components/StripeElementsFormUI/index.js
example/components/StripeRedirectFormUI/index.js
example/views/Home/index.js
example/views/PaymentOptionCashExample/index.js
example/views/PaymentOptionPaypalExample/index.js
example/views/PaymentOptionStripeDirectExample/index.js
example/views/PaymentOptionStripeExample/index.js
example/views/PaymentOptionStripeRedirectExample/index.js
package-lock.json
package.json
src/components/PaymentOptionCash/index.js
src/components/PaymentOptionPaypal/PaypalButton/index.js
src/components/PaymentOptionPaypal/index.js
src/components/PaymentOptionStripe/index.js
src/components/PaymentOptionStripeDirect/index.js
src/components/PaymentOptionStripeRedirect/StripeRedirectForm/index.js
src/components/PaymentOptionStripeRedirect/index.js
src/components/StripeElementsForm/CardForm/index.js
src/components/StripeElementsForm/index.js

Payment Option Stripe Redirect

---

example/components/LanguagesExample/index.js
example/components/MomentOptionUI/index.js
example/components/OrderReviewUI/index.js
example/views/MomentOptionExample/index.js
example/views/OrderReviewExample/index.js
src/components/AddressForm/index.js
src/components/AddressList/index.js
src/components/LanguageSelector/index.js
src/components/MomentOption/index.js
src/components/OrderReview/index.js
src/components/Popup/index.js
src/contexts/LanguageContext/index.js
src/contexts/OrderContext/index.js

https://www.loom.com/share/f0be16b60f804bf38d22bab2420ccc4a

[FIX] ReviewOrder

---

example/views/GoogleLoginExample/index.js
src/components/GoogleLoginButton/index.js

https://www.loom.com/share/f7182c60f61e4fa4a35eb2c6a1290b67

[FIX] GoogleLogin

---

example/components/ProductShareUI/index.js
example/views/ProductShareExample/index.js
src/components/ProductShare/index.js

https://www.loom.com/share/11ff61ea007e49b3bf12bc8e158c9476

[FIX] ProductShare

---

example/components/ProductShareUI/index.js
example/views/ProductShareExample/index.js
src/components/ProductShare/index.js

I use https://www.addtoany.com/

[FEAT] Change widget to share links

---

example/components/LanguageSelectorUI/index.js
src/components/LanguageSelector/index.js

[FIX] Catch errors in languages selector

---

example/components/BusinessBasicInformationUI/index.js
example/views/BusinessBasicInformationExample/index.js
src/components/BusinessBasicInformation/index.js

[FIX] Catch error in business basic information

---

src/components/BusinessList/index.js

- When user changes filters (categories, search), a glitch appears on business listing

[FIX] glitch on business listing

---

src/components/UpsellingPage/index.js

Fix upselling page

---

example/views/AddressDetailsExample/index.js
src/components/AddressDetails/index.js

[FIX] zoom out for addressDetailsMap

---

example/views/MessagesExample/index.js
src/components/Messages/index.js

- updating messages when order status changes

[FIX] messages when status changes

---

src/components/ProductForm/index.js

Cancel fetch on product form when component is unmounted

---

src/components/AddressDetails/index.js

https://app.asana.com/0/1191220738645130/1199226540685286

[FIX] icon marker

---

src/components/Popup/index.js

[FEAT] close modal onkeydown ESC

---

src/components/BusinessAndProductList/index.js

https://www.loom.com/share/e9322acbbaf44655b07b544c41172f7c

Featured products

---

src/components/AddressForm/index.js
src/components/GoogleMaps/index.js

https://www.loom.com/share/7fe5cc6a58354b50b49de282d63798b8

[FEAT] marker of the map for change location when drag

---

src/components/FacebookLoginButton/index.js

https://www.loom.com/share/56296913f9ed4bba85d24b4e4b1cdc23

[FIX] script of facebook sdk

---

src/components/UpsellingPage/index.js

https://www.loom.com/share/7057d5877aa24b59b8074e6e661949f2

(upselling) delete products that are sold out

---

src/components/GoogleAutocompleteInput/index.js

Google input autocomplete

---

cypress/integration/naked/resetPassword.spec.js
example/App.js
example/components/ResetPasswordUI/index.js
example/views/Home/index.js
example/views/ResetPasswordExample/index.js
src/components/ResetPassword/index.js
src/index.js

https://www.loom.com/share/0d1867f71dc04a63bb6d5514e3788717

[ADD] Reset Password Component

---

src/components/ExamineClick/index.js

[ADD] prop accept for examine click

---

src/components/FacebookLoginButton/index.js

[FIX] script of facebook

---

src/components/Cart/index.js

https://www.loom.com/share/47ad975e607a4ba58390bd993146fdb8

[FIX] business_id value

---

src/components/UserFormDetails/index.js

https://www.loom.com/share/63bee33026654134879812832da0dcca

[ADD] update changes for only user photo

---

src/components/Checkout/index.js
src/contexts/OrderContext/index.js

https://app.asana.com/0/1191220738645130/1199676402046789
https://www.loom.com/share/3ac649fbb4214fa88b6ffca37ed635f7
https://www.loom.com/share/617f0180be41464b9cf5e9e6f909e795

Delete delivery zone id in order type diff from 1

---

src/components/BusinessList/index.js

https://www.loom.com/share/09f3de404ae34f2ebbde921377bb6c42

Fix business search when press special keys

---

example/App.js
example/components/ResetPasswordUI/index.js
example/views/ResetPasswordExample/index.js
src/components/ResetPassword/index.js

https://www.loom.com/share/827c0babc4a64fbf885d84b5ae0f7757

Reset Password improvements

---

src/components/FacebookLoginButton/index.js

[FIX] cannot read prop login of undefined (Facebook)

---

src/components/Checkout/index.js

[FIX] undefined properties

---

src/components/StripeElementsForm/CardForm/index.js

props of null cardForm elements

---

src/components/PaymentOptionStripe/index.js

Payment cards

---

src/components/AddressDetails/index.js

[FIX] marker design

---

src/components/OrderDetails/index.js
src/components/ProductShare/index.js
src/contexts/ConfigContext/index.js

Add validations for share order and set configs

---

src/components/BusinessList/index.js
src/components/PaymentOptionStripe/index.js

Add sort function by review
Add initial filter by search value

Add sort function by review

---

src/contexts/UtilsContext/index.js

Change conversion factor from km to miles from 1km = 1.621371mi to 1km = 0.621371mi

change miles convertion value to the correct one.

---

src/components/PaymentOptionStripe/index.js

Payment options stripe

---

example/components/PhoneAutocompleteUI/index.js
src/components/PhoneAutocomplete/index.js

[ADD] button for active dropdown

---

src/contexts/OrderContext/index.js

Improve reorder method

---

src/components/BusinessList/index.js
src/components/ProductForm/index.js

Product form

---

package-lock.json
src/contexts/ApiContext/index.js
src/contexts/OrderingContext/index.js

Reverts Ordering-Inc/ordering-components#374

Revert "Context"

---

src/components/ProductOptionSuboption/index.js

Fix input radio ordering web app

Fix input radio ordering web app

---

src/components/ProductForm/index.js

now the products' with only one suboption is checked automatically 
Story: https://app.asana.com/0/1191220738645130/1200533823945514

[ADD] autoselect product suboption if it's just one

---

src/components/BusinessController/index.js

[ADD] time to close business

---

src/components/BusinessController/index.js

[FIX] business will close when business has more than one lapsus

---

src/contexts/OrderContext/index.js
src/contexts/OrderingContext/index.js

Reverts Ordering-Inc/ordering-components#424

Revert "Add theme for context"

---

src/components/BusinessController/index.js

Improved validation inside useEffect.

Fix: avoid set state repeatedly

---

src/components/BusinessList/index.js

https://app.asana.com/0/1191220738645130/1200555360910074

[ADD] save pagination businesslist

---

src/components/GoogleLoginButton/index.js

short unused code (GOOGLE LOGIN)

---

src/components/BusinessAndProductList/index.js

Fix Featured Products

---

src/components/ProductForm/index.js

Custom default suboptions for Starbucks 
video:
https://d.pr/v/3BiMYk

Custom default suboptions for Starbucks

---

src/contexts/UtilsContext/index.js

Fix AM/PM time

---

src/components/OrderDetails/index.js

this Pr depends on the https://github.com/Ordering-Inc/ordering-api-sdk/pull/29

gadd new ordering fetch (neccesary test with sdk updated)

---

src/components/GoogleMaps/index.js

adding custom funcionality in GoogleMap component

fix: aading custom popup an first business in GoogleMap component

---

src/components/BusinessList/index.js
src/components/OrderReview/index.js

Story: https://app.asana.com/0/inbox/1200268243109536/1199982295275783/1200740509990552

Franchise template

---

src/components/UpsellingPage/index.js

Upselling for all delivery types
Video
https://d.pr/v/FXFrn8

Upselling for all delivery types

---

src/components/GoogleMaps/index.js

https://app.asana.com/0/1191220738645130/1200994101769978

[fix] popup business googlemap

---

src/contexts/OrderContext/index.js

https://d.pr/v/EYC7lo https://app.asana.com/0/1191220738645130/1200994487627770

[add] toast for quick add product

---

src/components/GoogleMaps/index.js

https://app.asana.com/0/1191220738645130/1200998874951000

[fix] google maps old markers on map

---

src/components/OrderReview/index.js

Story: https://app.asana.com/0/1200268243113852/1199732808555394

Update: OrderReview

---

src/components/Contacts/index.js
src/components/UserFormDetails/index.js
src/contexts/ValidationsFieldsContext/index.js

Now when when available status from user is updated, is calling ChangeUser for update the state, with this it isn't necessary use refreshSession prop from ui. There's not task on asana.

add new prop error to validationField state

---

src/components/PaymentOptionPaypal/index.js

Story: https://app.asana.com/0/319423429024482/1201012353840878

[FIX] Paypal Currency

---

src/components/OrderList/index.js
src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/1200505565811868/1201034859704038
Story: https://app.asana.com/0/1200505565811868/1201032169367886

add new loading state and improve error message

---

src/contexts/OrderContext/index.js

Story:  https://app.asana.com/0/1199511033583011/1201019474591661/f
Video: https://d.pr/v/jXbEFn

[FIX] OrderType for unregistered users

---

src/components/BusinessList/index.js
src/components/Checkout/index.js

Story: https://app.asana.com/0/1200517202404523/1201050810896962/f

Update configs businessload

---

src/components/GoogleIdentity/index.js

Better implementation of google login

[add] google identity

---

src/components/GoogleMaps/index.js

Story: https://app.asana.com/0/1200268243113852/1201428600146258

[Update]: googleMap for franchise template

---

src/contexts/OrderContext/index.js

https://app.asana.com/0/1191220738645130/1201350124421558

[add] toast when product updated by quick add product

---

src/components/OrderList/index.js

Story: https://app.asana.com/0/0/1201455806345385/f

[FIX] socket for my order list

---

src/components/AddressList/index.js

Story: https://app.asana.com/0/1199511033583011/1201501544225799/f
Video: https://d.pr/v/M7oO2j

[FIX] no permission message

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1200268243113852/1201532548230196

Update: franchise business

---

src/components/GoogleMaps/index.js

Story: https://app.asana.com/0/1199511033583011/1201626834163028/f
Video: https://d.pr/v/AKY5pB

[FIX] Google map in order details

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/0/1201609384822489/f
Video: https://d.pr/v/nVfW0J

[FIX] search by product validation

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/1199511033583011/1201639998008081/f
Video: https://d.pr/v/LuVf4W

[FIX] Product load when moment change

---

src/components/OrderDetails/index.js
src/components/OrderList/index.js

Story: https://app.asana.com/0/1200550251832819/1201323980480080/f
Demo: https://d.pr/v/yNPFu1

some bug for profile message page

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1201115702325003/1201254712904266/f
Image: https://d.pr/i/0vqcvo

[FIX] removed repeated param and added location

---

src/components/FacebookLoginButton/index.js

Added a console.log for test in production versions with Yair

[ADD] facebook rerequest email

---

src/components/BusinessReviews/index.js

[FIX] loading in review component

[FIX] loading in review component

---

src/components/Checkout/index.js

Story: https://app.asana.com/0/0/1201844160893640/f

[FIX] amount in checkout

---

src/components/GoogleMaps/index.js

STORY: https://app.asana.com/0/1198717964402573/1201931522586220

[Fix] feedback for template franchise

---

src/components/PaymentOptions/index.js

Story: https://app.asana.com/0/1199511033583011/1201936820213166/f
Video: https://d.pr/v/iR0Omq

[FIX] add credentiales in payment data.

---

src/components/ProductForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1202094817158019
Demo: https://d.pr/v/YnJxwY

[Fix] cart product balance for shared menu

---

src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/1201324366625225/1202018122784459/f

[FIX] reload when cart update

---

src/components/OrderDetails/index.js

Story:  https://github.com/Ordering-Inc/Ordering-UI-Native/pull/744#discussion_r859857105
related screen :   https://d.pr/i/uBTeDm

Add handle reorder

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1201953052195819

Update: product form

---

src/components/Checkout/index.js

STORY: https://app.asana.com/0/1198717964402573/1202271877726673

[Add] fetch props for wallets configs

---

src/components/LoginForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1202253505195821

[Add] validation for native

---

src/components/BusinessAndProductList/index.js
src/components/OrderDetails/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202224356221558

Feedback reorder

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1200268243113852/1202342562473414

Update: ribbon

---

src/components/Sessions/index.js

STORY: https://app.asana.com/0/1198717964402573/1202352983490910

[update] Sessions

---

src/components/OrderListGroups/index.js

Story: https://app.asana.com/0/1199511033583011/1202362736162320/f

[FEAT] New order status

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1199511033583011/1202364574645600/f
Video: https://d.pr/v/OwE4Qm

[FEAT] fix fetch stores

---

native/index.js

STORY: https://app.asana.com/0/inbox/1198717964396322/1202405520675565/1202408251319319

import for native

---

src/components/OrderDetails/index.js

Story: https://app.asana.com/0/1199511033583011/1202398853248388/f
Video: https://d.pr/v/e8Pxss

[FEAT] Blank screen when order update

---

native/src/contexts/OrderingContext/index.js
src/contexts/WebsocketContext/index.js

Story: https://app.asana.com/0/0/1202522124261463/f

[FEAT] improve socket

---

src/components/BusinessSearchList/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202511437694494

get tag information

---

src/components/DriverTips/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202379385928727

update parseInt to parseFloat in driverTip

---

src/components/BusinessSearchList/index.js

STORY: https://app.asana.com/0/1198717964402573/1202555027059750

[Add] default term

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202175610551124

update remove product text

---

src/constants/code-numbers.js

STORY: https://app.asana.com/0/1198717964402573/1202594533209982

[Add] constant for Mauritius

---

src/components/MultiCartsPaymethodsAndWallets/index.js

STORY: https://app.asana.com/0/inbox/1198717964396322/1202625099398700/1202544086266330

[Update] multi payments

---

src/components/MultiCheckout/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202511437694520

multi checkout

---

src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202630333391244

update recaptcha validation text

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1202473893483636

[Update]: Booking functionality

---

src/components/BusinessList/index.js

STORY: https://app.asana.com/0/1198717964402573/1202661100351228

[Update] businesses

---

src/components/LoginForm/index.js
src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202677874577115

setting login and signup

---

src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202677874577115

signup settings

---

src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202677842084342

feedback improve signup

---

src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/1200550251832819/1202677623030909

update order context

---

src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202778798838779

feedback signup settings

---

src/components/BusinessController/index.js

STORY: https://app.asana.com/0/1198717964402573/1202778987595616

[Fix] crash bug

---

src/components/SingleOrderCard/index.js

Story: https://app.asana.com/0/1200268243113852/1202787208769552

Customer feedback

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/1200268243113852/1202809773061076

Update: booking-feedback

---

src/components/BusinessAndProductList/index.js

STORY: https://app.asana.com/0/1198717964402573/1202790511101916

[Fix] products search for using parent category

---

src/contexts/BillingContext/index.js

Reverts Ordering-Inc/ordering-components#787

Revert "[FEAT] update billing context"

---

src/components/OrderDetails/index.js

Story: https://app.asana.com/0/1200268243113852/1202790369874165

Update: feedback

---

src/components/MultiCheckout/index.js

STORY: https://app.asana.com/0/1198717964402573/1202931119467557

[Add] validation for wallets

---

package.json
src/components/LoginForm/index.js
src/components/ReCaptcha/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202909265940554

Feedback recaptchav3

---

src/components/LoginForm/index.js
src/components/ReCaptcha/index.js
src/components/SignupForm/index.js

Story: https://app.asana.com/0/home/1200550251832815/1202909265940554

Add recaptchav3

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203144781893971

[Update]: max amount of product

---

src/components/Checkout/index.js

demo template 5: https://www.loom.com/share/010d03255b354499af15b68d4bdce058
demo template 1: https://www.loom.com/share/b3f774fd25004f56a0579dfbe33dee25

[Fix] paymethods did not refresh when delivery type change

---

src/components/PromotionsController/index.js

STORY: https://app.asana.com/0/1198717964402573/1203123651501986

[Fix] promotions error for specific site

---

src/components/UserFormDetails/index.js

demo App: https://www.loom.com/share/58f5deb7e3754724a90d88c73bac17a1
demo Web: https://www.loom.com/share/9a911d9ee0694ceb830cf13bdb1d5ef0

[Add] enable/disable marketing notifications

---

src/components/BusinessController/index.js

STORY: https://app.asana.com/0/1198717964402573/1203295298962911

[Fix] favorite action

---

src/components/Checkout/index.js

story: https://app.asana.com/0/0/1203462140613951/f
demo App: https://www.loom.com/share/f743b7565a094dca867c49fd14eda281
demo Web: https://www.loom.com/share/412fe00990e2415db288a27cee382679

[Update] save table number with place order

---

src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/1199511033583011/1203422541705549/f
demo: https://www.loom.com/share/94aebb9b27394549ae1575c2198b664a

[Fix] copy paste number did not show auto-suggestion

---

src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/0/1203516403941670/f
demo: https://www.loom.com/share/c0ba96d240764da4b89e13cf345d2bac

call center feedback

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1203512546616174

[Fix] banner according to result type

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1203534292292647

[Fix] banner images

---

src/components/Cart/index.js
src/components/CouponControl/index.js
src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/1199511033583011/1203428923672622/f
Video: https://d.pr/v/ynPhQo

[FEAT] fix apply offer for callcenter

---

src/components/BusinessAndProductList/index.js
src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203580203471885

[Fix]: professional times

---

src/components/ProductOptionSuboption/index.js

story: https://app.asana.com/0/1199511033583011/1203582490127028/f

[Fix] plus signal enabled when should be disabled

---

src/components/CouponControl/index.js

Story: https://app.asana.com/0/0/1203622592521407/f

[FEAT] fix user id

---

src/components/OrderListGroups/index.js

story: https://app.asana.com/0/0/1203621848257999/f

[Fix] delivery app crashes when clicking on AL module

---

src/components/ProductForm/index.js

story: https://app.asana.com/0/1199511033583011/1203582422462680/f

[Fix] minimun to order on product form from search

---

src/components/OrderListGroups/index.js

Story: https://app.asana.com/0/1199511033583011/1203618299682526/f

[FEAT] filter orders level 2 user

---

src/components/PhoneAutocomplete/index.js

Story: https://app.asana.com/0/1199511033583011/1203695595807612/f
Video: https://d.pr/v/SxAGja

[FEAT] fix phone filter by user enabled

---

src/components/PhoneAutocomplete/index.js

Reverts Ordering-Inc/ordering-components#876

Revert "[FEAT] fix phone filter by user enabled"

---

src/components/PhoneAutocomplete/index.js

Story: https://app.asana.com/0/1199511033583011/1203695595807612/f

[FEAT] filter by user enabled

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/1199511033583011/1203716150183317/f
Video: https://d.pr/v/I1EF5W

[FEAT] prop avoidProductDuplicate

---

src/components/FirebaseGoogleLoginButton/index.js

STORY: https://app.asana.com/0/1198717964402573/1203705283552677

[Update] Google login for user info

---

src/components/LoginForm/index.js

Story: https://app.asana.com/0/1200268243113852/1203803620267194

[Update]: login for guest checkout

---

src/components/ProductForm/index.js
src/components/SignupForm/index.js

Story: https://app.asana.com/0/1203665030940611/1203861647278719/f
video: https://d.pr/v/jZ5zw1

[FEAT] fixes for call center

---

src/components/OrderDetails/index.js
src/components/OrderList/index.js

STORY: https://app.asana.com/0/1198717964402573/1203827976826217

[Fix] Messages are not marked as read

---

src/components/OrderDetails/index.js
src/components/OrderListGroups/index.js

story: https://app.asana.com/0/1199511033583011/1203863016401817/f

Drive app fixes al

---

package.json

Story: https://app.asana.com/0/1199511033583011/1203893499830102/f
Issue: firebase/firebase-js-sdk#7005

[FEAT] update firebase lib

---

src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/1203665030940611/1203920709498401/f

[FEAT] fix duplicate xappx

---

src/components/LoginForm/index.js

STORY: https://app.asana.com/0/1198717964402573/1203877725425735

[Fix] OTP issue when project is changed

---

src/components/OrderList/index.js
src/components/PaymentOptionStripe/index.js

story: https://app.asana.com/0/1199511033583011/1203802187527538/f

Feedback jan 25

---

src/components/ReCaptcha/index.js

story: https://app.asana.com/0/1199511033583011/1203905728364140/f

[Fix] recaptcha disappears

---

src/components/PromotionsController/index.js

story: https://app.asana.com/0/0/1203962405561196/f

[Fix] app goes blank when click on promotions

---

src/components/PageBanner/index.js
src/components/ReviewProduct/index.js
src/contexts/OrderContext/index.js

STORY: https://app.asana.com/0/1198717964402573/1203958790153743

[Add] events for Segment

---

src/components/PaymentOptionStripe/index.js

STORY: https://app.asana.com/0/1198717964402573/1203946316439075

[Fix] card list issue in App

---

src/components/ProductForm/index.js
src/components/SingleProductCard/index.js
src/contexts/OrderContext/index.js

STORY: https://app.asana.com/0/1198717964402573/1204016242406082

[Add] Wishlisting events for Segment

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204080321263252

[Update]: preselect fix

---

src/components/ReviewDriver/index.js

story: https://app.asana.com/0/1201894042190305/1204013908283660/f

[Fix] review order group

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/home/1200268243109536/1204080321263252

[Update]: product suboption preselect

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1200268243113852/1204092749362954

[Update]: open preorder popup

---

src/components/ReviewDriver/index.js
src/components/ReviewProduct/index.js

story: https://app.asana.com/0/1201894042190305/1204013908283660/f

[Fix] review product for multi business

---

src/components/ReviewProduct/index.js

story: https://app.asana.com/0/1201894042190305/1204013908283660/f

[Fix] review every product in multi business

---

src/components/MultiCheckout/index.js

story: https://app.asana.com/0/1199511033583011/1204218963691349/f

[Fix] multi business checkout redirect

---

src/components/GoogleMaps/index.js

Story: https://app.asana.com/0/0/1204239578710539/f

[FEAT] fix zipcode issue

---

src/components/Checkout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204412434089100

[Add] address notes param

---

src/components/GoogleMaps/index.js

Story: https://app.asana.com/0/1200268243113852/1204335314395668

[Feat]: delivery zone on business map

---

src/components/BusinessAndProductList/index.js
src/components/OrderList/index.js

story: https://app.asana.com/0/1199511033583011/1204487956763052/f

[Fix] fixes for website feedback

---

src/components/BusinessController/index.js

story: https://app.asana.com/0/1201894042190305/1204522296664769/f

[Add] error key lang for favorite

---

src/components/AddressList/index.js

STORY: https://app.asana.com/0/1198717964402573/1204316314999211

[Fix] sentry issue

---

src/components/OrderList/index.js

STORY: https://app.asana.com/0/1198717964402573/1204591370980134

[Add] new where condition to get the orders

---

src/components/MultiCheckout/index.js

Story: https://app.asana.com/0/1200268243113852/1204566686293728

[Update]: guest multi checkout

---

src/contexts/UtilsContext/index.js

Story: https://app.asana.com/0/inbox/1200268243109536/1204664744190277/1204668688454238

[Update]: fix language key

---

src/contexts/LanguageContext/index.js

story: https://app.asana.com/0/1199511033583011/1204670361124306/f

[Fix] set default languague when app starts

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/0/1204695885179041/f

[FEAT] add prop isApp

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1204592094895327

[Update] banner functionality

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/1200268243113852/1204771586300616

[Update]: fix product load for subcategory

---

src/components/BusinessAndProductList/index.js

story: https://app.asana.com/0/1199511033583011/1204771586300611/f

[Fix] order category by rank in the first call

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/1200268243113852/1204758891869340

[Update]: allow enable/disable for store app

---

src/contexts/LanguageContext/index.js

story: https://app.asana.com/0/1199511033583011/1204670361124306/f

[Update] change language when app starts

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1204786905521509

[Fix] wrong format location for banner

---

src/components/OrderListGroups/index.js

story: https://app.asana.com/0/1199511033583011/1204834609758489/f

[Feat] externa_id filter

---

src/components/MultiCartCreate/index.js
src/components/MultiCheckout/index.js

STORY: https://app.asana.com/0/1198717964402573/1204908336467994

[Fix] gift card cart issue when multi checkout is enabled

---

src/components/Checkout/index.js

Story: https://app.asana.com/0/1200268243113852/1204729057889963

[Update]: guest checkout settings

---

src/components/ProductForm/index.js

Story: https://app.asana.com/0/1200268243113852/1204945188326234

[Update]: booking update

---

native/src/contexts/OrderingContext/index.js
src/contexts/OrderContext/index.js

STORY: https://app.asana.com/0/1198717964402573/1204891491157575

[Add] Custom User Agent for React Native

---

src/components/FavoriteList/index.js

story: https://app.asana.com/0/1199511033583011/1204856679295808/f

[Fix] get favorites by order type

---

src/components/OrderListGroups/index.js

story: https://app.asana.com/0/1199511033583011/1204921712312370/f

[Feat] combine tabs and hide timer for delivery app

---

src/components/OrdersDashboardComponents/DashboardOrdersList/index.js
src/components/OrdersDashboardComponents/ExportCSV/index.js
src/components/OrdersDashboardComponents/OrdersManage/index.js

Story: https://app.asana.com/0/1199511033583011/1205040329603175/f

[FEAT] call-center-order-manager-franchise

---

src/components/GiftCard/GiftCardOrdersList/index.js

STORY: https://app.asana.com/0/1198717964402573/1205041016994256

[Add] orderBy for gift card orders

---

src/components/LoginForm/index.js

story: https://app.asana.com/0/1199511033583011/1204945440937701/f

[Update] lang key for mono session error message

---

src/components/OrderListGroups/index.js

story: https://app.asana.com/0/1199511033583011/1204921712312370/f

[Fix] refresh active orders when new order comes

---

src/components/PaymentOptionStripe/index.js

story: https://app.asana.com/0/1199511033583011/1205145085063477/f

[Fix] refresh card list after new card was added

---

src/components/PageBanner/index.js

story: https://app.asana.com/0/1199511033583011/1205146198376836/f

[Fix] banners keeps on skeleton loader

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1205014083370206

[Add] time stamp for banner

---

src/components/BusinessController/index.js

story: https://app.asana.com/0/1199511033583011/1205146198376883/f

[Fix] validadte when discount its 0

---

src/contexts/OrderContext/index.js

STORY: https://app.asana.com/0/inbox/1198717964396322

[Add] product cart info to Product Added event

---

src/components/AddressForm/index.js

story: https://app.asana.com/0/0/1205066153005174/f

[Fix] redirect issue for new users

---

src/components/BusinessList/index.js

story: https://app.asana.com/0/1199511033583011/1205066153005174/f

[Fix] refresh user info in business list to prevent redirect

---

src/components/PageBanner/index.js

STORY: https://app.asana.com/0/1198717964402573/1205235172893883

[Fix] page banner issue

---

src/components/PageBanner/index.js

story: https://app.asana.com/0/1199511033583011/1205146198376836/f

[Fix] banners keeps loading

---

src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/1199511033583011/1204842492179974/f

[Fix] fixes for callcenter new feature: get phone from url

---

src/components/BusinessList/index.js
src/components/LoginForm/index.js
src/components/PaymentOptions/index.js
src/contexts/SessionContext/index.js

story: https://app.asana.com/0/1199511033583011/1204451811414109/f

[Feat] get paymethods by device kiosk

---

src/components/PhoneAutocomplete/index.js

story: https://app.asana.com/0/0/1205317374222593/f

callcenter feedback

---

src/contexts/LanguageContext/index.js

story: https://app.asana.com/0/1199511033583011/1205235475469751/f

[Fix] loading bug

---

src/contexts/LanguageContext/index.js

story: https://app.asana.com/0/1199511033583011/1205235475469751/f

[Fix] languages issue

---

src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/0/1205379777985520/f

[FEAT] validation-is-disable-toast

---

src/components/AddressForm/index.js

story: https://app.asana.com/0/1199511033583011/1205144809732696/f

[Fix] franchise filter

---

src/components/UserFormDetails/index.js

story : https://app.asana.com/0/1199511033583011/1205055751054854/f

[Fix] driver status loader issue

---

src/components/GoogleMaps/index.js

story: https://app.asana.com/0/1199511033583011/1205144809732696/f

[Fix] fallback icon for business in google maps

---

src/components/UserFormDetails/index.js
src/contexts/SessionContext/index.js

story: https://app.asana.com/0/1199511033583011/1205055751054854/f

[Fix] logout driver from dashboard

---

src/components/GoogleMaps/index.js

story: https://app.asana.com/0/1199511033583011/1205144809732696/f

[Fix] logo fallback

---

src/components/UserFormDetails/index.js
src/contexts/SessionContext/index.js

story: https://app.asana.com/0/1199511033583011/1205055751054854/f

[Update] logout only when it is disabled

---

src/components/PaymentOptionStripe/index.js

story: https://app.asana.com/0/1199511033583011/1205490937295943/f

[Fix] issue when deleting a card can not end the payment

---

src/contexts/OrderContext/index.js

Story: https://app.asana.com/0/0/1205379777985520/f

[FEAT] disable toast prop for add product

---

src/components/StripeElementsForm/CardForm/index.js

story: https://app.asana.com/0/1199511033583011/1205490937295943/f

[Fix] bearer token undefined

---

src/components/UserFormDetails/index.js

story: https://app.asana.com/0/1199511033583011/1205599744665225/f

[Fix] sometimes id it is not being sent

---

src/components/OrderDetails/index.js

sotry: https://app.asana.com/0/1199511033583011/1205598560486797/f

[Fix] fixes for messages dot

---

src/components/GoogleMaps/index.js

Story: https://app.asana.com/0/0/1205790263227477/f

[FEAT] fix-call-center-map-zones

---

src/components/OrdersDashboardComponents/OrdersManage/index.js

Story: https://app.asana.com/0/0/1205806633088965/f

[FEAT] add agent column

---

src/components/BusinessAndProductList/index.js

story: https://app.asana.com/0/1199511033583011/1205916976145343/f

[Fix] fix rank and a-z filter

---

src/components/FacebookLoginButton/index.js

Story: https://app.asana.com/0/0/1206362316296878/f

[FEAT] fix facebook

---

src/contexts/LanguageContext/index.js

Story: https://app.asana.com/0/1199511033583011/1206351584046006/f
Video: https://d.pr/v/7Uo7GV

[FEAT] fix language change

---

src/components/UserFormDetails/index.js

Story: https://app.asana.com/0/0/1206587082431499/f

[FEAT] fix

---

src/components/ProductItemAccordion/index.js

Story: https://app.asana.com/0/1199511033583011/1206331517969167/f

[FEAT] fix-sort-product-options

---

native/index.js

Story: https://app.asana.com/0/0/1206879562872735/f

[FEAT] fix missing import

---

src/components/LoginForm/index.js

Story: https://app.asana.com/0/1199511033583011/1207049315409535/f

[FEAT] fix login callcenter

---

src/components/OrderList/index.js

Story: https://app.asana.com/0/1199511033583011/1207093525861026/f

[FEAT] fix-where-consult

---

package.json
src/components/ProductForm/index.js
yarn.lock

Story: https://app.asana.com/0/0/1207592433611703/f

[FEAT] remove sentry

---

src/components/BusinessList/index.js

Story: https://app.asana.com/0/1164464536714178/1207859896651513/f

[FEAT] fix-loading-business-list-call-center

---

src/components/PaymentOptionStripeLink/index.js
src/components/PaymentOptions/index.js
src/index.js

Story: https://app.asana.com/0/1164464536714178/1208468965897293/f

Refactor PaymentOptionStripeLink component and add PaymentOptionStripeLink to PaymentOptions

---

src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1164464536714178/1208530725003388/f

Refactor UpsellingPage component to include suggestive upselling feature

---

src/components/Checkout/index.js

Story: https://app.asana.com/0/0/1208612983397325/f

Refactor Checkout component to include handleOrderRedirect function

---

src/components/PaymentOptionStripeLink/index.js

Story: https://app.asana.com/0/1164464536714178/1208602367363143/f

Refactor PaymentOptionStripeLink component to handle error message in setStripeLinkState

---

src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1164464536714178/1208640832020884/f

Refactor: Improve handling of upselling products in UpsellingPage component

---

src/components/ProductForm/index.js
src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1164464536714178/1208717999119422/f

Refactor ProductForm and UpsellingPage components for improved null safety and API integration

---

src/components/UpsellingPage/index.js

Story: https://app.asana.com/0/1201540673559408/1208751721946597/f

Refactor: Enhance getUpsellingProducts function to allow optional inclusion of all products

---

src/components/PaymentOptionStripeLink/index.js

Story: https://app.asana.com/0/0/1208767403599288/f

Refactor: Update provider selection logic in PaymentOptionStripeLink component to support custom providers

---

src/components/BusinessAndProductList/index.js

Story: https://app.asana.com/0/0/1209108713827867/f

Refactor BusinessAndProductList component to enhance product mapping with category slugs

---

src/components/GoogleAutocompleteInput/index.js
src/components/GoogleMaps/index.js
src/components/GpsButton/index.js

Story: https://app.asana.com/0/1164464536714178/1209126625571252/f

Refactor Google Autocomplete components to improve city retrieval logic and enhance address mapping

---

src/components/PaymentOptionStripeLink/index.js

Story: https://app.asana.com/0/1164464536714178/1209209284902443/f

Enhance PaymentOptionStripeLink component to include cart total and user information in payment request

---

src/components/ProductOptionSuboption/index.js

Story: https://app.asana.com/0/1164464536714178/1209259258289778/f

Refactor ProductOptionSuboption to improve half-option and quantity selection logic
